---
title: 中断
created: 2022-05-12 10:27:34
updated: 2022-05-12 20:11:06
tags: 
- atom
---
# 中断

线程中断即线程运行过程中被其他线程给打断了。

## 原理

- 中断无法直接终止另一[[3-计算机科学/2-计算机组成原理/线程|线程]]，只能发起通知。
- 中断需要被中断线程自己处理。
- 每个对象有一boolean标识是否有中断请求（来自其它线程/自身）。
	- 线程 t1 想中断线程 t2，只需要在线程 t1 中将线程 t2 对象的中断标识置为 true，然后线程 t2 可以选择在合适的时候处理该中断请求，甚至可以不理会该请求，就像这个线程没有被中断一样。

java.lang.Thread 类提供了几个方法来操作这个中断状态，这些方法包括：
- `public static boolean interrupted()`：测试**当前**线程是否已经中断。线程的中断状态由该方法清除。换句话说，如果连续两次调用该方法，则第二次调用将返回 false（在第一次调用已清除了其中断状态之后，且第二次调用检验完中断状态前，当前线程再次中断的情况除外）。
- `public boolean isInterrupted()`：测试**目标**线程（由具体Thread实例决定）是否已经中断。线程的中断状态不受该方法的影响。
- `public void interrupt()`：中断**目标**线程，给目标线程发一个中断信号，线程被打上中断标记即将中断状态设置为true。

### 响应中断

假设某个线程要不停地处理某件事情(比如 i 一直自增)，但是还有个要求：在处理事情前，先要检查下这个线程是否被中断，如果已经被中断，处理就应该结束。

下面是一些例子：
```java
public class Run {
 
    public static void main(String[] args) {
        try {
            MyThread thread = new MyThread();
            thread.start();
            Thread.sleep(20);//modify 2000 to 20
            thread.interrupt();//请求中断MyThread线程
        } catch (InterruptedException e) {
            System.out.println("main catch");
            e.printStackTrace();
        }
        System.out.println("end!");
    }
}
```
main线程睡眠20ms后，执行第8行中断MyThread线程：
```java
public class MyThread extends Thread {
    @Override
    public void run() {
        super.run();
        for (int i = 0; i < 500000; i++) {
            if (this.interrupted()) {
                System.out.println("should be stopped and exit");
                break;
            }
            System.out.println("i=" + (i + 1));
        }
        System.out.println("this line is also executed. thread does not stopped");//尽管线程被中断,但并没有结束运行。这行代码还是会被执行
    }
}
```
当MyThread获得CPU执行时，第6行的 if 测试中，检测到中断标识被设置。即MyThread线程检测到了main线程想要中断它的 请求。

大多数情况下，MyThread检测到了中断请求，**对该中断的响应是：退出执行（或者说是结束执行）。**

但是，上面第5至8行for循环，是执行break语句跳出for循环。但是，线程并没有结束，它只是跳出了for循环而已，它还会继续执行第12行的代码....

**因此，我们的问题是，当收到了中断请求后，如何结束该线程呢？**

一种可行的方法是使用 return 语句 而不是 break语句。。。。。哈哈。。。

**当然，一种更优雅的方式则是：抛出InterruptedException异常。**

看下面MyThread类的代码：
```java
public class MyThread extends Thread {
    @Override
    public void run() {
        super.run();
        try{
            for (int i = 0; i < 500000; i++) {
                if (this.interrupted()) {
                    System.out.println("should be stopped and exit");
                    throw new InterruptedException();
                }
                System.out.println("i=" + (i + 1));
            }
            System.out.println("this line cannot be executed. cause thread throws exception"); //这行语句不会被执行!!!
        }catch(InterruptedException e){
            System.out.println("catch interrupted exception");
            e.printStackTrace();
        }
    }
}
```

注意，这个例子中的输出结果看起来可能有问题，比如有几行在插入一个元素之后，队列的剩余空间不变。这是由于**System.out.println语句没有锁**。考虑到这样的情况：线程1在执行完put/take操作后立即失去CPU时间片，然后切换到线程2执行put/take操作，执行完毕后回到线程1的System.out.println语句并输出，发现这个时候阻塞队列的size已经被线程2改变了，所以这个时候输出的size并不是当时线程1执行完put/take操作之后阻塞队列的size，但可以确保的是size不会超过10个。实际上使用阻塞队列是没有问题的。

### 线程池中使用阻塞队列

```java
public ThreadPoolExecutor(int corePoolSize,
                           int maximumPoolSize,
                           long keepAliveTime,
                           TimeUnit unit,
                           BlockingQueue<Runnable> workQueue) {
        this(corePoolSize, maximumPoolSize, keepAliveTime, unit, workQueue,
             Executors.defaultThreadFactory(), defaultHandler);
}
```